//
//  APIWorker.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol APIStoreProtocol {
    func fetchTop(after afterTag: String?, completionHandler: @escaping (_ entries: [EntryModel], _ afterTag: String?) -> (), errorHandler: @escaping (_ message: String) -> ())
}

class APIWorker {
    
    var store: APIStoreProtocol
    
    init(store: APIStoreProtocol) {
        self.store = store
    }
    
    func fetchTop(after afterTag: String?, completionHandler: @escaping (_ entries: [EntryModel], _ afterTag: String?) -> (), errorHandler: @escaping (_ message: String) -> ()) {
        store.fetchTop(after: afterTag, completionHandler: completionHandler, errorHandler: errorHandler)
    }
}
