//
//  URLDetailPresenter.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol URLDetailPresentationLogic {
    func presentUIInfo(response: URLDetail.UIInfo.Response)
    func presentFavoriteAction(response: URLDetail.FavoriteAction.Response)
}

class URLDetailPresenter: URLDetailPresentationLogic {
    weak var viewController: URLDetailDisplayLogic?
    
    func presentUIInfo(response: URLDetail.UIInfo.Response) {
        if let url = response.item.url {
            let heartImage = MainEntryPresenter.getHeartImage(isFavorite: response.item.isFavorite)
            viewController?.displayUIInfo(viewModel: URLDetail.UIInfo.ViewModel(url: url, image: heartImage))
        }
    }
    
    func presentFavoriteAction(response: URLDetail.FavoriteAction.Response) {
        guard let errorMessage = response.errorFound else {
            let heartImage = MainEntryPresenter.getHeartImage(isFavorite: response.item.isFavorite)
            viewController?.displayFavoriteActionSuccessful(viewModel: URLDetail.FavoriteAction.ViewModel.Successful(image: heartImage))
            return
        }
        let alertController = UIAlertController(title: Localized.Strings.issuesWiththeDB.rawValue, message: errorMessage, preferredStyle: .alert)
        let okAction = UIAlertAction(title: Localized.Strings.ok.rawValue, style: .default, handler: nil)
        alertController.addAction(okAction)
        viewController?.displayFavoriteActionErrorFound(viewModel: URLDetail.FavoriteAction.ViewModel.ErrorFound(alertController: alertController))
    }
    
}
