//
//  URLDetailInteractor.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol URLDetailBusinessLogic {
    func requestUIInfo(request: URLDetail.UIInfo.Request)
}

protocol URLDetailDataStore {
    var item: EntryModel? {get set}
}

class URLDetailInteractor: URLDetailBusinessLogic, URLDetailDataStore {
    var presenter: URLDetailPresentationLogic?
    
    var item: EntryModel?
    
    func requestUIInfo(request: URLDetail.UIInfo.Request) {
        if let item = item {
            presenter?.presentUIInfo(response: URLDetail.UIInfo.Response(item: item))
        }
    }
}
