//
//  URLDetailPresenter.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol URLDetailPresentationLogic {
    func presentUIInfo(response: URLDetail.UIInfo.Response)
}

class URLDetailPresenter: URLDetailPresentationLogic {
    weak var viewController: URLDetailDisplayLogic?
    
    func presentUIInfo(response: URLDetail.UIInfo.Response) {
        if let url = response.item.url {
            let heartImage = response.item.isFavorite ? UIImage(named: Assets.images.heartEnabled.rawValue) :  UIImage(named: Assets.images.heartDisabled.rawValue)
            viewController?.displayUIInfo(viewModel: URLDetail.UIInfo.ViewModel(url: url, image: heartImage))
        }
    }
}
