//
//  FavoritesInteractor.swift
//  freeza
//
//  Created by Cesar Brenes on 12/17/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class FavoritesInteractor: MainEntryBusinessLogic, MainEntryDataStore {

    var presenter: MainEntryPresentationLogic?
    
    func requestDataStore(request: MainEntry.DataStore.Request) {
        //presenter?.presentDataSource(response: MainEntry.DataStore.Response(prueba: "Favorites"))
    }
    
    func requestDetail(request: MainEntry.Detail.Request) {
        
    }
}
