//
//  MainEntryModels.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainEntry {
    
    enum DataStore {
        struct Request {
        }
        struct Response {
            var items: [EntryModel]
            var errorMessage: String?
            var safePreference: Bool
        }
        struct ViewModel {
            struct Successful {
                var items: [ItemToDisplay]
            }
            struct ErrorFound {
                var message: String
            }
        }
    }
    
    enum Detail {
        struct Request {
            var indexPath: IndexPath
        }
        struct Response {
            var item: EntryModel
            var indexPath: IndexPath
            var safePreference: Bool
        }
        struct ViewModel {
            struct Successful {
                var url: URL
            }
            struct ErrorFound {
                var indexPath: IndexPath
            }
        }
    }
    
    enum Favorite {
        struct Request {
            var indexPath: IndexPath
        }
        struct Response {
            var indexPath: IndexPath
            var item: EntryModel
            var safePreference: Bool
        }
        struct ViewModel {
            var indexPath: IndexPath
            var item: ItemToDisplay
        }
    }
    
    struct ItemToDisplay {
        var thumbnailImageURL: URL?
        var author: String
        var commentCount: String
        var time: String
        var title: String
        var heartImage: UIImage?
        var shouldHideContent: Bool
    }
}
