//
//  MainEntryRouter.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainEntryRoutingLogic {
    func goToDetailViewController(url: URL)
}

protocol MainEntryDataPassing {
  var dataStore: MainEntryDataStore? { get }
}

class MainEntryRouter: NSObject, MainEntryRoutingLogic, MainEntryDataPassing {
  weak var viewController: MainEntryViewController?
  var dataStore: MainEntryDataStore?
  
    func goToDetailViewController(url: URL) {
        let storyboard = UIStoryboard(name: Storyboard.ReferenceName.main.rawValue, bundle: nil)
        if let urlViewController = storyboard.instantiateViewController(withIdentifier: ViewControllerReference.Name.urlViewController.rawValue) as? URLViewController {
            urlViewController.url = url
            viewController?.navigationController?.pushViewController(urlViewController, animated: true)
        }
    }
}
