//
//  MainEntryInteractor.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainEntryBusinessLogic {
    func requestDataStore(request: MainEntry.DataStore.Request)
    func requestDetail(request: MainEntry.Detail.Request)
    func requestFavorite(request: MainEntry.Favorite.Request)
    var presenter: MainEntryPresentationLogic? {get set}
}

protocol MainEntryDataStore {
    
}

class MainEntryInteractor: MainEntryBusinessLogic, MainEntryDataStore {
    
    var businessLogic: MainEntryBusinessLogic
    
    var presenter: MainEntryPresentationLogic? {
        didSet {
            businessLogic.presenter = presenter
        }
    }
    
    init(businessLogic: MainEntryBusinessLogic) {
        self.businessLogic = businessLogic
    }
    
    func requestDataStore(request: MainEntry.DataStore.Request) {
        businessLogic.requestDataStore(request: request)
    }
    
    func requestDetail(request: MainEntry.Detail.Request) {
        businessLogic.requestDetail(request: request)
    }
    
    func requestFavorite(request: MainEntry.Favorite.Request) {
        businessLogic.requestFavorite(request: request)
    }
}
