//
//  SettingsRouter.swift
//  freeza
//
//  Created by Cesar Brenes on 12/17/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SettingsDataPassing {
  var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing {
  weak var viewController: SettingsViewController?
  var dataStore: SettingsDataStore?
  
}
