//
//  SettingsModels.swift
//  freeza
//
//  Created by Cesar Brenes on 12/17/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {
    // MARK: Use cases
    
    enum DataSource {
        struct Request {
        }
        struct Response {
            var items: [Item]
        }
        struct ViewModel {
            var items: [ItemToDisplay]
        }
    }
    
    enum SetValue {
        struct Request {
            var indexPath: IndexPath
            var value: Bool
        }
    }
    
    enum Option {
        case safe
    }
    
    struct ItemToDisplay {
        var title: String
        var value: Bool
    }
    
    struct Item {
        var type: Option
        var value: Bool
    }
}
