//
//  SettingsWorker.swift
//  freeza
//
//  Created by Cesar Brenes on 12/17/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SettingsWorker {
    
    func createDataSource(worker: LocalQuickStorageWorker) -> [Settings.Item] {
        return [Settings.Item(type: .safe, value: worker.get(key: User.Defaults.safe.rawValue) as? Bool ?? false)]
    }
}
