//
//  MainEntryPresenter.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainEntryPresentationLogic {
  func presentDataSource(response: MainEntry.DataStore.Response)
}

class MainEntryPresenter: MainEntryPresentationLogic {
  weak var viewController: MainEntryDisplayLogic?
  
  // MARK: Do something
  
  func presentDataSource(response: MainEntry.DataStore.Response) {
//    let viewModel = MainEntry.DataStore.ViewModel(prueba: response.prueba)
//    viewController?.displayDataSource(viewModel: viewModel)
  }
}
