//
//  MainEntryModels.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainEntry {
    
    enum DataStore {
        struct Request {
        }
        struct Response {
            var items: [EntryModel]
        }
        struct ViewModel {
            struct Successful {
                var items: [ItemToDisplay]
            }
            struct ErrorFound {
                
            }
        }
    }
    
    struct ItemToDisplay {
        var thumbnailImageURL: URL?
        var author: String
        var commentCount: Int
        var time: String
        var title: String
        var heartImage: UIImage
        var shouldHideContent: Bool
    }
}
