//
//  TopEntriesViewController.swift
//  freeza
//
//  Created by Cesar Brenes on 12/18/20.
//  Copyright (c) 2020 Zerously. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class TopEntriesViewController: MainEntryViewController {
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup(businessLogic: MainEntryStoreInteractor(businessLogic: TopEntriesInteractor()))
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup(businessLogic: MainEntryStoreInteractor(businessLogic: TopEntriesInteractor()))
    }
    
    // MARK: View lifecycle
    
    let moreButton = UIButton(type: .system)
    let tableFooterView = UIView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func dataFinishedToReload() {
        super.dataFinishedToReload()
        self.moreButton.isEnabled = true
        tableView.tableFooterView = tableFooterView
    }
    
    override func configureTableView() {
        super.configureTableView()
        tableFooterView.frame = CGRect(x: 0, y: 0, width: self.view.bounds.width, height: 80)
        tableFooterView.addSubview(self.moreButton)
        moreButton.frame = self.tableFooterView.bounds
        moreButton.setTitle("More...", for: [])
        moreButton.setTitle("Loading...", for: .disabled)
        moreButton.titleLabel?.font = UIFont.boldSystemFont(ofSize: 16)
        moreButton.addTarget(self, action: #selector(TopEntriesViewController.moreButtonTapped), for: .touchUpInside)
    }
    
    @objc func moreButtonTapped() {
        self.moreButton.isEnabled = false
        requestDataSource()
    }
    
}
